[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 20, fail_on_revert = false }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
